### PR TITLE
Add callback func for thermostat target

### PR DESCRIPTION
**Pull request by tomtaylor**
Following on from #29, here's some code to expose changes to the thermostat target temperature in the same manner as the switch.

### CODE REVIEW

**Comment by brutella** [comment]
Looks good. 

But it's better to define a method in the `Thermostat` interface under `hc/model/thermostat.go`. Then implement the method in `thermostat` struct and change the field name from `OnTargetTempChange func(float64)` to `onTargetTempChange func(float64)` to make it private.

**Comment by tomtaylor** [comment]
Of course, yes. My Go is a bit rusty. Have another look at the latest commit.

**Comment by brutella** [comment]
Nice 👍

**Comment by tomtaylor** [comment]
Thanks!

**Pull request merged**
