### PR TITLE
add support for setup hash

### LINKED ISSUE #105: Are there plans to support setup codes?
We need to advertise `sh` as part of the bonjour service defined in 4.2.4 setup codes. Are there any plans to add this support?

See also https://github.com/KhaosT/HAP-NodeJS/blob/c62294b3c5400157164a10a1e96a41259c3fc23b/lib/Advertiser.js#L70

### PR DESCRIPTION
**Pull request by chris-rock**
This fixes #105 and announces the setup hash via bonjour to enable the use of setup codes with this project.

If you like, I can also add the support to generate the `X-HM:` url generation for the qr code generation

### CODE REVIEW

**Comment by brutella** [comment]
I can't find any info in the non-commercial HAP documentation about the setup hash. Is this documented somewhere?

**Comment by chris-rock** [comment]
This is reverse engineered and is not part of the non-commercial HAP documentation. A similar approach is used in https://github.com/KhaosT/HAP-NodeJS/blob/c62294b3c5400157164a10a1e96a41259c3fc23b/lib/Advertiser.js#L24 and https://github.com/nfarina/homebridge/issues/1588

**Comment by brutella** [comment]
What is it used for?

**Comment by chris-rock** [comment]
I am too lazy to enter the setup code in my App. Have a look at http://lollyrock.com/articles/homekit-for-fritzbox/

**Comment by brutella** [comment]
`X-HM` url generation would be great and would go hand in hand with this pull request.

**Comment by FernFerret** [comment]
Here's an implementation I've been using alongside `hc` to generate the `X-HM://` url (that can be easily added as a QR Code, which is how I'm using it). I just stitched in the base36 encoding rather than adding another dependency, so that may be a place you'd want to change; but I'd love to get both of these features into `hc` so I didn't have to carry around my own fork with @chris-rock's `setupHash`.

https://gist.github.com/FernFerret/a6b97250766879406578f192294a0e56

**Comment by brutella** [comment]
Thanks for your contribution. 🎉

**Comment by brutella** [comment]
[ipTransport.XHMURI()](https://github.com/brutella/hc/blob/master/ip_transport.go#L216) now returns a X-HM styled uri.

**Pull request merged**
