### PR TITLE
Garage Door Opener

### PR DESCRIPTION
**Pull request by Pmaene**
Started working on adding support for Garage Door Openers to HomeControl.

### CODE REVIEW

**Comment by brutella** [comment]
Nice, here are some changes to get this working

- Rename `Obstruction` characteristic to `ObstructionDetected`
- Rename `SetObstruction()` and `Obstruction()` to `SetObstructionDetected()` and `ObstructionDetected()`
- Use `TypeObstructionDetected` for `ObstructionDetected` characteristic (instead of `TypeObstruction`)
- Use `NewDoorState` instead of `NewHeatingCoolingMode` when creating new door state characteristic
- Use `model.DoorStateType` instead of `model.HeatCoolModeType` in method `DoorState()`

Additionally you have to create a **garage door opener service**, which consists of the current door state, target door state and obstruction detected characteristics, and a **garage door opener accessory** which uses the **garage door opener service** to implement the `GarageDoorOpener` interface.

**Comment by dwery** [comment]
@Pmaene still working on that?

**Comment by Pmaene** [comment]
@dwery It's still on my todo list, but I haven't been able to look into it the past few months. I'll try to finish it sometime in the coming weeks.

**Comment by brutella** [comment]
v0.1.0 now provides all pre-defined services and characteristics. Please use them.

**Comment by brutella** [comment]
The garage door opener service (as defined in HomeKit) is now available in the library since v0.1.0.

**Pull request closed without merging**
