### PR TITLE
use dep for vendoring and all missing dependencies

### PR DESCRIPTION
**Pull request by chris-rock**
This is a PR up for discussion and I am not sure you want to go this way. It uses [dep](https://github.com/golang/dep) as the dependency manager which makes it more easy to update the dependencies

### CODE REVIEW

**Comment by srizzling** [comment]
just as a btw, does using dep mean you have to commit everything under `.vendor`

**Comment by aidansteele** [comment]
I'm not au fait with the current state of the art for Golang dependency management, but the checked-in `vendor` directory is a real turn-off for me. 

I prefer using [`glide`](http://glide.sh/), which requires only a `glide.yaml` and `glide.lock` to be checked into source control. With `vendor` in `.gitignore`, you can just type `glide install` after cloning to vendor all the dependencies. It works like Ruby's `Gemfile[.lock]` or NodeJS' `package.json` and `package-lock.json`.

Also 👋 @srizzling

**Comment by chris-rock** [comment]
Go dep does not require do put in the vendor directory. We can opt for a `gopkg.toml` and `gopkg.lock`. I just put the vendored files in since the project has done it before. In my other projects I am not checking in vendor and it works like `glide` then.

**Comment by aidansteele** [comment]
@chris-rock thanks for the info - I should check out Go dep.

**Comment by srizzling** [comment]
Oh thanks for the info, Golang has kinda messed me up in terms of dependencies, I'm kinda struggling to find out how to do customization

Oh hai @aidansteele, with glide did you try using it with this project? I tried, but it kept erroring talking about type errors? It could be my setup.

**Comment by aidansteele** [comment]
@srizzling By "customisation", do you mean you are struggling to work on a fork of this project? If so, you can add this to your glide.yaml:

```yaml
- package: github.com/brutella/hc
  repo: https://github.com/srizzling/hc.git
```

That will clone from your fork, but using the upstream's import names.

**Comment by aidun** [comment]
I would put the vendor/ directory to the .gitignore

**Comment by chris-rock** [comment]
I am happy to update to just include the gopkg.toml and gopkg.lock file while removing the vendor directory. Is that the way this should go @brutella ?

**Comment by brutella** [comment]
This library now uses Go modules.

**Pull request closed without merging**
