### PR TITLE
implemented contact sensor

### PR DESCRIPTION
**Pull request by smitterson**
Hi there,

Awesome project! 

I've implemented the contact sensor accessory type.

See https://github.com/smitterson/hkdoorsensor for an example/test I made to verify this will work as a trigger in homekit.

### CODE REVIEW

**Comment by wolfspyre** [comment]
is anything preventing this being merged?

**Comment by brutella** [comment]
I've made some changes with the last commit.

@smitterson Could you please update the PR. I will merge it then.

**Comment by brutella** [comment]
v0.1.0 now provides all pre-defined services and characteristics. Please use them.

**Comment by brutella** [comment]
The contact sensor service (as defined in HomeKit) is now available in the library since `v0.1.0`.

**Pull request closed without merging**
